routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect()->route('movie.index'); 
});

Route::resource('/movie', 'MovieController')->names([
    'index' => 'movie.index',
    'create' => 'movie.create',
    'edit' => 'movie.edit',
    'store' => 'movie.store',
    'update' => 'movie.update',
    'delete' => 'movie.delete'
]);

Route::get('/api', 'UpdateApiData')->name('apiUpdate');

app/Genre.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Genre extends Model
{
  protected $fillable = ['title'];
}

app/Movie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
    protected $fillable = ['title', 'synopsis'];

    public function genres()
    {
        return $this->belongsToMany('App\Genre');
    }

    public function participants()
    {
        return $this->hasMany('App\Participant');
    }

    public function getGenresIdsAttribute()
    {
        return $this->genres->pluck('id');
    }
}

app/Participant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Participant extends Model
{
  protected $fillable = ['name', 'role_id', 'movie_id'];

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }
}

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = ['name'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use App\Movie;
use App\Genre;
use App\Role;
use App\Participant;
use Illuminate\Http\Request;

class MovieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $movies = Movie::all();
        return view('movie.index', compact('movies')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $genres = Genre::all();
        $roles = Role::all();
        return view('movie.create', compact('genres', 'roles')); 
    }

    /**
     * Store a newly created participant in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function storeParticipant($movieId, $participant)
    {
      $participant = Participant::create([
          'name' => $participant['name'],
          'role_id' => $participant['role'],
          'movie_id' => $movieId
      ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'title' => 'required|string',
            'synopsis' => 'required|string',
            'genres' => 'array',
            'participants' => 'string'
        ]);
        $movie = Movie::create($data);
        $movie->genres()->attach($data['genres']);
        foreach (json_decode($data['participants'], true) as $participant) {
            $participant = Participant::create([
                'name' => $participant['name'],
                'role_id' => $participant['role'],
                'movie_id' => $movie->id
            ]);
        }

        return redirect()->route('movie.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function show(Movie $movie)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function edit(Movie $movie)
    {
        $genres = Genre::all();
        $roles = Role::all();
        return view('movie.edit', compact('genres', 'roles', 'movie')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Movie $movie)
    {
        $data = $request->validate([
            'title' => 'required|string',
            'synopsis' => 'required|string',
            'genres' => 'array',
            'participants' => 'string'
        ]);
        $movie->update($data);
        $movie->genres()->sync($data['genres']);

        foreach (json_decode($data['participants'], true) as $participant) {
						if (isset($participant['id'])) {
								$finded = Participant::find($participant['id']);

								$finded ->update([
										'name' => $participant['name'],
										'role_id' => $participant['role']
								]);
						} else {
								Participant::create([
										'name' => $participant['name'],
										'role_id' => $participant['role'],
										'movie_id' => $movie->id
								]);
						}
        }

        return redirect()->route('movie.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function destroy(Movie $movie)
    {
				$movie->delete();
        return redirect()->route('movie.index');
    }
}

app/Http/Controllers/UpdateApiData.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Movie;
use App\Participant;
use Illuminate\Support\Facades\Storage;

class UpdateApiData extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
		$contents = Storage::disk('local')->get('selecao.xml');
        $xml = simplexml_load_string($contents);

        foreach($xml as $item) {
			$movie = Movie::find($item->attributes()->id);
			if ($movie) {
				$movie->update([
					'title' => strval($item->titulo),
					'synopsis' => strval($item->resumo),
				]);

            	$genres = [];
            	foreach((array)$item->genero as $index => $title) {
                	$genres[] = $index + 1;
            	}

				foreach ($movie->participants as $data) {
    				$data->delete();
				}

        		$movie->genres()->sync($genres);
					foreach ((array)$item->elenco->ator as $participant) {
						$participant = Participant::updateOrCreate([
							'name' => $participant,
							'role_id' => 2,
							'movie_id' => $movie->id
						]);
					}
        	} else {

					$movie = Movie::create([
						'title' => strval($item->titulo),
						'synopsis' => strval($item->resumo),
					]);

					$genres = [];
					foreach((array)$item->genero as $index => $title) {
						$genres[] = $index + 1;
					}
					$movie->genres()->attach($genres);

					foreach ((array)$item->elenco->ator as $participant) {
						$participant = Participant::updateOrCreate([
							'name' => $participant,
							'role_id' => 2,
							'movie_id' => $movie->id
						]);
					}
			}

        }

		$movies = Movie::all();
        return view('movie.index', compact('movies'));
    }
}

resources/views/layouts/base.blade.php
<!doctype html>
<html>

<head>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ url('/css/styles.min.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link rel="shortcut icon" type="image/png" href="{{ url('favicon.png')}}"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{{ url('/css/principal.css')}}">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <title>Filmoteca</title>
</head>

<style>
    .select2-container .select2-selection--single,
    .select2-container--default .select2-selection--single .select2-selection__arrow {
        height: 38px;
    }

    .select2-container--default .select2-selection--single .select2-selection__rendered {
        line-height: 38px;
    }

    .select2-container--default .select2-selection--single {
        border: 1px solid #ced4da;
    }

    .select2-container {
        width: 100% !important;
    }

    .pagination-container{
        margin-top: 15px;
        display: flex;
        justify-content: center;
    }

    .pagination-container > .pagination{
        margin-bottom: 0;
    }
    .select2-search--inline {
      display: contents;
    }
    .select2-search__field:placeholder-shown {
      width: 100% !important;
    }

</style>

@yield('custom_css')
<script>

    function tabDefault() {
        $('#pesqTab a:first').tab('show');
    }
    (function() {
        $("select2-IDProjetoRelacionado -container").select2({ width: 'resolve' });
    });

    window.addEventListener("load", tabDefault);
    window.addEventListener("load", function () {
        $('[data-toggle="tooltip"]').tooltip()
    });

</script>

<body>
	<div class="wrapper">
		<div id="content">
			<div class="container-fluid">
					@yield('content')
			</div>
		</div>
	</div>
	<script src="{{ asset('js/app.js') }}" defer></script>
	<script src="{{url('/')}}/js/functions.js"></script>
</body>

</html>

resources/views/movie/create.blade.php
@extends('layouts.base')

@section('content')
<div class="card mt-3 mb-3">
  <div class="card">
    <div class="card-header h5">Novo Filme</div>
    <div class="card-body">
        <a href="{{ route('movie.index') }}" title="Voltar">
          <button class="btn btn-warning btn-sm">
            <i class="fa fa-arrow-left" aria-hidden="true"></i>Voltar
          </button>
        </a>
        <br />
        <br />

        @if(session('success'))
        <div class="alert alert-success" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          {{session('success')}}
        </div>
        @endif

        @if ($errors->any())
        <ul class="alert alert-danger">
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
        @endif

        <form
          method="POST"
          action="{{ url('/movie') }}"
          accept-charset="UTF-8"
          class="form-horizontal"
          enctype="multipart/form-data"
          >
          {{ csrf_field() }}

          @include ('movie.form', ['formMode' => 'create'])
        </form>
    </div>
  </div>
</div>
@endsection

resources/views/movie/edit.blade.php
@extends('layouts.base')

@section('content')
<div class="card mt-3 mb-3">
  <div class="card">
    <div class="card-header h5">{{ $movie->title }}</div>
    <div class="card-body">
        <a href="{{ route('movie.index') }}" title="Voltar">
          <button class="btn btn-warning btn-sm">
            <i class="fa fa-arrow-left" aria-hidden="true"></i>Voltar
          </button>
        </a>
        <br />
        <br />

        @if(session('success'))
        <div class="alert alert-success" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          {{session('success')}}
        </div>
        @endif

        @if ($errors->any())
        <ul class="alert alert-danger">
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
        @endif

        <form
          method="POST"
          action="{{ route('movie.update', $movie->id) }}"
          accept-charset="UTF-8"
          class="form-horizontal"
          enctype="multipart/form-data"
          >
          @method('PUT')
          {{ csrf_field() }}

          @include ('movie.form', ['formMode' => 'edit'])
        </form>
    </div>
  </div>
</div>
@endsection

resources/views/movie/form.blade.php
<div class="form-row">
  <div class="form-group col-md-6">
    <label for="name" class="obrigatorio control-label h6">Titulo do Filme</label>
    <input autofocus class="form-control" type="text" placeholder="Nome" name="title" id="title"
      @if(isset($movie))
        value="{{ $movie->title }}"/>
      @else
        value="{{ old('title')}}"/>
      @endif
    {!! $errors->first('title', '<small class="text-danger">:message</small>') !!}
  </div>

  <div class="form-group col-md-6">
    <label for="genres" class="obrigatorio control-label h6">Genêros</label>
    <select class="multiple-selector" name="genres[]" multiple="multiple">
      @foreach($genres as $genre)
        <option value="{{ $genre->id }}">{{ $genre->title }}</option>
      @endforeach
    </select>
    {!! $errors->first('value', '<small class="text-danger">:message</small>') !!}
  </div>
  <div class="col-md-12 col-lg-8">
    <label for="synopsis" class="obrigatorio control-label h6">Resumo</label>
    <div class="form-group" width="100%">
      <textarea name="synopsis" width="100%" id="synopsis" value="www">
      </textarea>
    </div>
  </div>
</div>

<div id="app">
@if(isset($movie))
  <cast-list :roles="{{ $roles }}" :cast="{{ $movie->participants->toJson() }}"></cast-list>
@else
  <cast-list :roles="{{ $roles }}"></cast-list>
@endif
</div>

<div class="form-group">
  <button class="btn btn-primary" type="submit">
    <i class="fas fa-save"></i> {{ $formMode === 'edit' ? 'Salvar alterações' : 'Concluir cadastro' }}
  </button>
</div>

<script src="https://cdn.tiny.cloud/1/kkz10avk1rv0256g2mqjuwu53wah5cxe38v7x98effpfhkzh/tinymce/5/tinymce.min.js"
  referrerpolicy="origin"
>
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
@if(isset($movie))
  <script>
    tinymce.init({
      selector: 'textarea#synopsis',
      init_instance_callback: "insert_contents",
      menubar: false
    });

    function insert_contents(inst){
      inst.setContent("{!! $movie->synopsis !!}");
    }

		$(document).ready(function() {
			$('.multiple-selector').select2();
			$('.multiple-selector').val({{ $movie->getGenresIdsAttribute() }}).change();
		});

  </script>
@else
  <script>
    tinymce.init({
      selector: 'textarea#synopsis',
      menubar: false
    });

		$(document).ready(function() {
			$('.multiple-selector').select2();
		});
  </script>
@endif

resources/views/movie/index.blade.php
@extends('layouts.base')

@section('content')
<div class="card mt-3 mb-3">
  <div class="card">
    <div class="card-header h5">Lista de Filmes</div>
    <div class="card-body">
      <div class="mb-3 d-flex flex-row-reverse">
        <a href="{{ route('movie.create') }}" class="btn btn-success btn-sm" title="Cadastrar Area">
          <i class="fa fa-plus" aria-hidden="true"></i> Cadastrar
        </a>
      </div>
      <div class="mb-3 d-flex flex-row-reverse">
        <a href="{{ route('apiUpdate') }}" class="btn btn-success btn-sm" title="Cadastrar Area">
          <i class="fa fa-plus" aria-hidden="true"></i> Dados da API
        </a>
      </div>
      <div class="row">
        <div class="col-md-12">

            @if(session('success'))
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-check"></i> Sucesso!</h4>
                {{session('success')}}
            </div>
            @endif

            @if (isset($errors) && count($errors) > 0)
            <div class="alert alert-danger alert-dismissible flat no-margin">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Whoops!</strong><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
        </div>
      </div>

      <div class="table-responsive">
        <table class="table table-striped table-index table-index-td">
          <thead>
            <tr>
              <th>#</th>
              <th>Titulo</th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            @foreach($movies as $movie)
            <tr>
              <td class="h6">{{ $movie->id }}</td>
              <td class="h6">{{ $movie->title }}</td>
              <td>
                <a href="{{ route('movie.edit', $movie->id) }}" title="Editar">
                  <button class="btn btn-primary btn-sm mr-1"><i class="fa fa-edit" aria-hidden="true"></i></button>
                </a>
                <form
									method="POST"
									action="{{ route('movie.destroy', $movie->id) }}"
									accept-charset="UTF-8"
									style="display:inline"
									>
									{{ method_field('DELETE') }}
                  {{ csrf_field() }}
									<button
										type="submit"
										class="btn btn-danger btn-sm"
										title="Excluir Disciplina"
										onclick="return confirm('Confirmar exclusão?')"
										>
										<i class="fa fa-trash" aria-hidden="true"></i>
									</button>
                </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

@endsection